In [785]:
import pygad
import numpy as np

In [786]:
n = 8

def createBoard(n: int) -> list[list[int]]:
    return np.zeros((n, n), dtype=int)

boardToShow = createBoard(n)
print("Board:\n", boardToShow)

Board:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [787]:
def fulfillBoard(solution: list[int]) -> list[list[int]]:
    board = createBoard(n)
    
    for i in range(len(solution)):
        x = solution[i]
        board[i][x] = 1

    return board

def checkColission(row: int, col: int, board: list[list[int]]) -> bool:
    n = len(board)
    
    # Check row and column
    if sum(board[row]) > 1 or sum([board[i][col] for i in range(n)]) > 1:
        return True
    
    # Check diagonal
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1 and (i, j) != (row, col):
            return True
    for i, j in zip(range(row, n), range(col, -1, -1)):
        if board[i][j] == 1 and (i, j) != (row, col):
            return True
    
    return False

def fitness_func(solution, solution_idx):
    newSol = solution.astype(int)
    attacks = 0
    board = fulfillBoard(newSol)

    for i in range(len(board)):
        for j in range(len(board[i])):
            if board[i][j] == 1:
                if checkColission(i, j, board):
                    attacks += 1
                    
    board = createBoard(n)
    return (attacks * -1)

fitness_function = fitness_func

In [788]:
#sss = steady, rws=roulette, rank = rankingowa, tournament = turniejowa
parent_selection_type = "sss"
crossover_type = "single_point"
mutation_type = "random"
mutation_percent_genes = 8

In [789]:
n = 2

gene_space = np.arange(n)
sol_per_pop = 50
num_genes = n
num_parents_mating = 20
num_generations = 100
keep_parents = 5

ga_instance = pygad.GA(gene_space=gene_space,
                       num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes)

ga_instance.run()

solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution.astype(int)))
print("Fitness value of the best solution = {solution_fitness}".format(
    solution_fitness=solution_fitness))

ga_instance.plot_fitness()

Parameters of the best solution : [1 0]
Fitness value of the best solution = -1


In [790]:
n = 8

gene_space = np.arange(n)
sol_per_pop = 50
num_genes = n
num_parents_mating = 20
num_generations = 100
keep_parents = 5

ga_instance = pygad.GA(gene_space=gene_space,
                       num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes)

ga_instance.run()

solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution.astype(int)))
print("Fitness value of the best solution = {solution_fitness}".format(
    solution_fitness=solution_fitness))

ga_instance.plot_fitness()

Parameters of the best solution : [4 7 3 0 6 1 5 2]
Fitness value of the best solution = 0


In [791]:
n = 20

gene_space = np.arange(n)
sol_per_pop = 450
num_genes = n
num_parents_mating = 120
num_generations = 300
keep_parents = 45

ga_instance = pygad.GA(gene_space=gene_space,
                       num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes)

ga_instance.run()

solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution.astype(int)))
print("Fitness value of the best solution = {solution_fitness}".format(
    solution_fitness=solution_fitness))

ga_instance.plot_fitness()

KeyboardInterrupt: 